### ISSUE TITLE
No kittens in repository 

### ISSUE THREAD

**Issue by De-ad** [Kaladin13/smart-house#1]
Hello! There’s no any kittens in this repo, please add at least one to continue! 😼
![IMG_4887](https://github.com/Kaladin13/smart-house/assets/75694495/06d93a0b-7714-4da9-8255-27eddedd5ade)

**Comment by Kaladin13** [comment]
@De-ad 

ฅ/ᐠ. ̫ .ᐟ\ฅ

**Comment by Kaladin13** [comment]
closing as done 😼
